name: Auto Update README

on:
  push:
    paths:
      - "**/*.md"

permissions:
  contents: write

jobs:
  update-readme:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Generate README
        run: python scripts/generate_readme.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          git add README.md

          git diff --cached --quiet || git commit -m "docs: update README table of contents"

          git push